server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/ms-user
spring.datasource.username=postgres
spring.datasource.password=231506

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

broker.queue.email.name=default.email
spring.rabbitmq.addresses=amqps://qagthnns:DAxJ-BcnK2EpR6JDYWkaUyk-LQ7IWdE0@fuji.lmq.cloudamqp.com/qagthnns